[phases.build]
# Entra a la carpeta 'backend' y luego instala las dependencias
cmds = ["cd backend && npm install"]

[start]
# Entra a la carpeta 'backend' y luego ejecuta el comando de arranque
cmd = "cd backend && npm start"