# Configuración explícita para Nixpacks (el sistema de Railway)

[phases.build]
# Le decimos que entre a la carpeta 'backend' y luego instale las dependencias
cmds = ["cd backend && npm install"]

[start]
# Le decimos que entre a la carpeta 'backend' y luego ejecute el comando de arranque
cmd = "cd backend && npm start"